version: '3.8'

services:
  mongodb:
    container_name: syntax-highlighting-service-mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
    volumes:
      - db-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
  rest-api:
    container_name: syntax-highlighting-service-rest-api
    build: ./rest.api
    image: benlegiang/syntax-highlighting-service-rest-api:master
    ports:
      - 8081:8081
    depends_on:
      - annotation-api
    restart: always
  annotation-api:
    container_name: syntax-highlighting-service-annotation-api
    build: ./annotation.api
    image: benlegiang/syntax-highlighting-service-annotation-api:master
    depends_on:
      - mongodb
    restart: always
volumes:
  db-data:
    


