version: '3.8'

services:
  mongodb:
    container_name: syntax-highlighting-service-mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
    volumes:
      - db-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    networks:
      - backend
    restart: unless-stopped
  prediction-api:
    container_name: syntax-highlighting-service-prediction-api
    build: ./prediction.api
    image: benlegiang/syntax-highlighting-service-prediction-api:master
    ports:
      - $PREDICTION_API_HOST_PORT:8000
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    networks:
      - backend 
  training-api:
    container_name: syntax-highlighting-service-training-api
    build: ./training.api
    image: benlegiang/syntax-highlighting-service-training-api:master
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    networks:
      - backend
  rest-api:
    container_name: syntax-highlighting-service-rest-api
    build: ./rest.api
    image: benlegiang/syntax-highlighting-service-rest-api:master
    ports:
      - $REST_API_HOST_PORT:8081
    depends_on:
      - annotation-api
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - backend    
    restart: always
  annotation-api:
    container_name: syntax-highlighting-service-annotation-api
    build: ./annotation.api
    image: benlegiang/syntax-highlighting-service-annotation-api:master
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1024M
    restart: always
    networks:
      - backend
volumes:
  db-data:
networks:
  backend:
    driver: bridge
    


