version: '3.8'

services:
  rest-api:
    container_name: syntax-highlighting-service-rest-api
    build: ./rest.api
    image: syntax-highlighting-service-rest-api:master
    environment:
      PORT: 8080
    restart: always
