version: '3.8'

services:
  rest-api:
    container_name: syntax-highlighting-service-rest-api
    build: ./rest.api
    image: benlegiang/syntax-highlighting-service-rest-api:master
    ports:
      - 8081:8081
    restart: always

  mongodb:
    container_name: syntax-highlighting-service-mongodb
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: annotations
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  db-data:
    


