name: Continuous Deployment on Remote Ubuntu VM
on:
  push:
    branches: master
    
jobs: 
  deploy:
    name: Deploy to VM
    runs-on: ubuntu-latest
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Create SSH Connection to VM
      uses: appleboy/ssh-action@master
      with:
        host: benlegiang.ch
        username: ${{secrets.UBUNTU_VM_USER}}
        key: ${{secrets.UBUNTU_VM_SECRET}}
        port: 22
        script: |
          cd syntax-highlighting-service
          git pull origin master
          bash deploy.sh
