name: Build - Publish - Deploy Prediction API Image

on:
  push:
    branches:
      - master
    paths:
      - prediction.api/**

jobs:
  push_to_registries:
    name: Push Prediction API to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: benlegiang/syntax-highlighting-service-prediction-api
      
      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: prediction.api/
          file: prediction.api/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    name: Deploy to Production
    needs: push_to_registries
    runs-on: ubuntu-latest
    steps:
    - name: Create SSH Connection to VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.UBUNTU_VM_HOST}}
        username: ${{secrets.UBUNTU_VM_USER}}
        key: ${{secrets.UBUNTU_VM_SECRET}}
        port: ${{secrets.UBUNTU_VM_PORT}}
        script: |
          docker login --username benlegiang --password-stdin < docker_pwd.txt
          cd syntax-highlighting-service
          git pull origin master
          bash deploy.sh
